### ISSUE TITLE
Crash when i do /is increasesize 300 "player name"

### ISSUE THREAD

**Issue by ViruZzInGame** [FrozenArea/RedSkyBlockX#1]
Error: str_replace(): Argument #2 ($replace) must be of type array|string, int given
File: plugins/RedSkyBlockX_dev-32.phar/src/RedCraftPE/RedSkyBlockX/Commands/SubCommands/IncreaseSize
Line: 38
Type: TypeError
Backtrace:
#0 plugins/RedSkyBlockX_dev-32.phar/src/RedCraftPE/RedSkyBlockX/Commands/SubCommands/IncreaseSize(38): str_replace(string[6] {SIZE}, int 300, string[69] ..aYou have changed ..fViruZzInGame's ..aisland size to ..f{SIZE}..a.)
#1 plugins/RedSkyBlockX_dev-32.phar/src/RedCraftPE/RedSkyBlockX/libs/CortexPE/Commando/BaseCommand(144): RedCraftPE\RedSkyBlockX\Commands\SubCommands\IncreaseSize->onRun(object pocketmine\player\Player#184540, string[2] is, array[2])
#2 pmsrc/src/command/SimpleCommandMap(212): RedCraftPE\RedSkyBlockX\libs\CortexPE\Commando\BaseCommand->execute(object pocketmine\player\Player#184540, string[2] is, array[2])
#3 pmsrc/src/Server(1415): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\player\Player#184540, string[32] is increasesize 300 ViruZzInGame)
#4 pmsrc/src/player/Player(1503): pocketmine\Server->dispatchCommand(object pocketmine\player\Player#184540, string[32] is increasesize 300 ViruZzInGame)
#5 pmsrc/src/network/mcpe/handler/InGamePacketHandler(818): pocketmine\player\Player->chat(string[33] /is increasesize 300 ViruZzInGame)
#6 pmsrc/vendor/pocketmine/bedrock-protocol/src/

**Comment by NhanAZ** [comment]
Please try using this build https://github.com/FrozenArea/RedSkyBlockX/suites/13365859486/artifacts/731100447

**Comment by ViruZzInGame** [comment]
I Used this build but I got another error, the plugin cant starter the server

Error: Cannot assign null to property NhanAZ\RedSkyBlockX\Utils\ZoneManager::$zoneWorld of type string
File: plugins/e40cd53904d5b31d.phar/src/NhanAZ/RedSkyBlockX/Utils/ZoneManager
Line: 61
Type: TypeError
Backtrace:
#0 plugins/e40cd53904d5b31d.phar/src/NhanAZ/RedSkyBlockX/SkyBlock(70): NhanAZ\RedSkyBlockX\Utils\ZoneManager->__construct(object NhanAZ\RedSkyBlockX\SkyBlock#40704)
#1 pmsrc/src/plugin/PluginBase(118): NhanAZ\RedSkyBlockX\SkyBlock->onEnable()
#2 pmsrc/src/plugin/PluginManager(454): pocketmine\plugin\PluginBase->onEnableStateChange(true)
#3 pmsrc/src/Server(1388): pocketmine\plugin\PluginManager->enablePlugin(object NhanAZ\RedSkyBlockX\SkyBlock#40704)
#4 pmsrc/src/Server(1032): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#40680)
#5 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[78] /storage/emulated/0/Android/data/com.kpwnapps.pmmpplugins/files/PocketMine-MP/, string[86] /storage/emulated/0/Android/data/com.kpwnapps.pmmpplugins/files/PocketMine-MP/pl)
#6 pmsrc/src/PocketMine(357): pocketmine\server()
#7 pmsrc(11): require(string[122] phar:///storage/emulated/0/Android/data/com.kpwnapps.pmmpplugins/files/PocketMin)

Code:
[52] 
[53] 	public function __construct(SkyBlock $plugin) {
[54] 		self::$plugin = $plugin;
[55] 		self::$zone = $plugin->skyblock->get("Zone", []);
[56] 		self::$zoneStartPosition = $plugin->skyblock->get("Zone Position", []);
[57] 		self::$zoneSize = $plugin->skyblock->get("Zone Size", []);
[58] 		self::$zoneSpawn = $plugin->skyblock->get("Zone Spawn", []);
[59] 		$zoneWorld = $plugin->skyblock->get("Zone World");
[60] 		if ($zoneWorld === false) {
[61] 			self::$zoneWorld = null;
[62] 		} else {
[63] 			if ($plugin->getServer()->getWorldManager()->loadWorld($zoneWorld)) {
[64] 				self::$zoneWorld = $plugin->getServer()->getWorldManager()->getWorldByName($zoneWorld);
[65] 			} else {
[66] 				self::$zoneWorld = false;
[67] 				$plugin->skyblock->set("Zone World", self::$zoneWorld);
[68] 			}
[69] 		}
[70] 		self::$zoneShovel = VanillaItems::WOODEN_SHOVEL();
[71] 		self::$zoneShovel->getNamedTag()->setByte("redskyblockx", 1);

Loaded plugins:
RedSkyBlockX 6.0.0-ALPHA by NhanAZ, RedCraftPE for API(s) 5.0.0

**Comment by NhanAZ** [comment]
Fixed
